[project]
name = "polylogue"
version = "0.1.0"
description = "a REST API, following the OpenAI API schema, that serves self-hosted, open-source ai models of all types"
readme = "README.md"
requires-python = ">=3.12"
pythonpath = ["src"]
dependencies = [
    "click>=8.4.2",
    "fastapi[standard]>=0.128.8",
    "llama-cpp-python>=0.3.35",
    "mlx>=0.29.3",
    "mlx-lm>=0.29.1",
    "openai",
    "pytest>=8.4.2",
    "redis>=7.0.1",
]

[dependency-groups]
dev = [
    "poethepoet",
]

[project.scripts]
polylogue = "polylogue:main"
polylogue-cli = "polylogue.cli:cli"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0", "hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
ignore = ["I001"]

[tool.hatch.build.targets.wheel]
packages = ["src/polylogue"]

[tool.pytest.ini_options]
pythonpath = ["src"]
# skip tests marked with @pytest.mark.slow by default
addopts = "-m 'not slow'"
markers = [
    "slow: marks tests as slow (deselected by default)",
]
