from collections.abc import Generator
from typing import Protocol, runtime_checkable


@runtime_checkable
class Model(Protocol):
    def load(self) -> None: ...

    def destroy(self) -> None: ...

    def generate(self, prompt: str) -> str: ...

    def stream_generate(self, prompt: str) -> Generator[str, None, None]: ...
