from typing import Protocol, runtime_checkable


@runtime_checkable
class DBClient[T](Protocol):
    async def hget(self, key: str, field: str) -> T | None: ...

    async def hset(self, key: str, field: str, value: T) -> int: ...

    async def hdel(self, key: str, field: str) -> int: ...

    async def hgetall(self, key: str) -> dict[str, T]: ...
