from collections.abc import Awaitable, Mapping
from typing import Protocol, runtime_checkable


@runtime_checkable
class DBClient[T](Protocol):
    async def hget(self, key: str, field: str) -> Awaitable[T | None]: ...

    async def hset(self, key: str, field: str, value: T) -> Awaitable[int]: ...

    async def hdel(self, key: str, field: str) -> Awaitable[int]: ...

    async def hgetall(self, key: str) -> Awaitable[Mapping[str, T]]: ...
