from collections.abc import Mapping
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DBClient[KeyT, ValueT](Protocol):
    async def hget(self, key: KeyT, field: KeyT) -> ValueT | None: ...

    async def hset(self, key: KeyT, field: KeyT, value: ValueT) -> int: ...

    async def hdel(self, key: KeyT, field: KeyT) -> int: ...

    async def hgetall(self, key: KeyT) -> Mapping[KeyT, ValueT]: ...

    async def smembers(self, name: str) -> set[str | bytes] | list[str | bytes]: ...

    def pipeline(self, transaction: bool = True) -> Any: ...


@runtime_checkable
class PipelineProtocol(Protocol):
    def hset(
        self,
        name: str,
        key: str | None = None,
        value: str | None = None,
        mapping: dict[str, Any] | None = None,
    ) -> Any: ...

    def sadd(self, name: str, *values: str) -> Any: ...

    def srem(self, name: str, *values: str) -> Any: ...

    def delete(self, *names: str) -> Any: ...

    async def execute(self) -> list[Any]: ...
