CHATML_TEMPLATE = (
    "{%- if messages[0]['role'] == 'system' %}"
    "{{- '<|im_start|>system\n' + messages[0]['content'] }}"
    "{%- set loop_messages = messages[1:] %}"
    "{%- else %}"
    "{{- '<|im_start|>system\nYou are a helpful assistant.' }}"
    "{%- set loop_messages = messages %}"
    "{%- endif %}"
    "{%- if tools %}"
    "{{- '\n\n# Tools\n\nYou have access to the following functions:\n\n' }}"
    "{%- for tool in tools %}"
    "{{- tool | tojson + '\n' }}"
    "{%- endfor %}"
    '{{- \'\nUse the following format for tool calls:\n<tool_call>\n{"name": "function_name", "arguments": {"arg1": "value1"}}\n</tool_call>\' }}'
    "{%- endif %}"
    "{{- '<|im_end|>\n' }}"
    "{%- for message in loop_messages %}"
    "{%- if message['role'] == 'developer' %}"
    "{{- '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' }}"
    "{%- elif message['role'] == 'user' %}"
    "{{- '<|im_start|>user\n' }}"
    "{%- if message['content'] is string %}"
    "{{- message['content'] }}"
    "{%- else %}"
    "{%- for part in message['content'] %}"
    "{%- if part['type'] == 'text' %}{{- part['text'] }}{%- endif %}"
    "{%- endfor %}"
    "{%- endif %}"
    "{{- '<|im_end|>\n' }}"
    "{%- elif message['role'] == 'assistant' %}"
    "{{- '<|im_start|>assistant\n' }}"
    "{%- if message.get('thinking') %}"
    "{{- '<think>\n' + message['thinking'] + '\n</think>\n' }}"
    "{%- elif message.get('reasoning_content') %}"
    "{{- '<think>\n' + message['reasoning_content'] + '\n</think>\n' }}"
    "{%- endif %}"
    "{%- if message.get('content') %}"
    "{%- if message['content'] is string %}"
    "{{- message['content'] }}"
    "{%- else %}"
    "{%- for part in message['content'] %}"
    "{%- if part['type'] == 'text' %}{{- part['text'] }}{%- endif %}"
    "{%- endfor %}"
    "{%- endif %}"
    "{%- endif %}"
    "{%- if message.get('tool_calls') %}"
    "{%- for tool_call in message['tool_calls'] %}"
    "{{- '<tool_call>\n{\"name\": \"' + tool_call['function']['name'] + '\", \"arguments\": ' }}"
    "{%- if tool_call['function']['arguments'] is string %}"
    "{{- tool_call['function']['arguments'] }}"
    "{%- else %}"
    "{{- tool_call['function']['arguments'] | tojson }}"
    "{%- endif %}"
    "{{- '}\n</tool_call>\n' }}"
    "{%- endfor %}"
    "{%- endif %}"
    "{{- '<|im_end|>\n' }}"
    "{%- elif message['role'] == 'tool' %}"
    "{{- '<|im_start|>tool\n' + message['content'] + '<|im_end|>\n' }}"
    "{%- endif %}"
    "{%- endfor %}"
    "{%- if add_generation_prompt %}"
    "{{- '<|im_start|>assistant\n' }}"
    "{%- if enable_thinking is defined and not enable_thinking %}"
    "{{- '<think>\n\n</think>' }}"
    "{%- endif %}"
    "{%- endif %}"
)
